### ISSUE TITLE
Unable to create databasefile

### ISSUE THREAD

**Issue by mindphaseproductions** [rcdailey/zandronum-server#5]
When running the server with: databasefile doom2db in a .cfg, I receive an error in the logs:
```shell
Can't open database "doom2db": unable to open database file
``` 

When running: databasefile filenamehere in a .cfg or in a server console, it's supposed to create a database file, or load a database file with the respective name. I'm not even sure where it would even attempt to create/load the file, as the information on this from Zandronum is not very clear.

Given that this setup is different from when running from the client, would you perhaps know how to resolve this?

Here's the following relevant details:

doom2.cfg - 
```shell
set sv_hostname "My Stronghold Server"
set sv_forcepassword true
set sv_password "test123"
authhostname auth.zandronum.com:16666
databasefile doom2db

addmap MAP99
```                                                                    

docker-compose details -
```dockerfile
zandronum_server:
    image: rcdailey/zandronum-server:official-latest
    container_name: zandronum_server
    restart: always
    network_mode: host
    command: >
      -port 10667
      -iwad /data/doom2.wad
      -file /data/strnghld_v1.pk3
      -file /data/strnghld_violence_v4.pk3
      -file /data/strongholdeditsnfixesv1.1patchv4.1.pk3
      -file /data/strongholditemsv7.1.pk3
      -file /data/strongholdrejuvenated-v6d.pk3
      -file /data/strongholdrejuvenated-colouredobituaries-v2.pk3
      +exec /configs/global.cfg
      +exec /configs/coop.cfg
      +exec /configs/doom2.cfg
      +exec /configs/flags.cfg
    volumes:
      - ./data:/data:ro
      - ./configs:/configs:ro
```

**Comment by rcdailey** [comment]
I've never used `databasefile` before, but I was able to find some relevant docs [here](https://wiki.zandronum.com/Version_history/1.3). Specifically:

> The new CVAR databasefile controls where the database is saved (defaults to ":memory:", i.e. volatile in-memory database)

One thing worth trying is an absolute path. Something like `databasefile /data/doom2.db`. Let me know how that goes.

**Comment by mindphaseproductions** [comment]
Thanks for the reply!

This got me one step closer to resolving this.

So essentially, it didn't work, but, I ended up creating a dummy doom2.db file in /data/, and then re-started the container, and it loaded the database succesfully this time, but with the error that it's not a real db file (because I created a dummy one with nano).

I'm assuming what I have to do is somehow generate a database file another way, and just put it in that directory. Will report back.

Thanks again for your help!

**Comment by rcdailey** [comment]
Yeah if it's not creating a valid database for you, you'll need to find a way for it to be created. Sounds like you're figuring it out. I'll go ahead and close this since I'm not seeing anything here to indicate a problem with the docker container itself.

**Comment by mindphaseproductions** [comment]
Yeah, this can be closed. There's nothing wrong with the docker container.

I resolved it by creating the database from the zandronum server client on another system, and copied the .db file /data on the docker-container machine. Just in-case anyone else wants to do this.
